# Generated by Django 4.0.1 on 2022-02-03 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_comment_options'),
        ('main_app', '0013_alter_comment_options_profilephoto'),
    ]

    operations = [
    ]
