# Generated by Django 4.0.1 on 2022-02-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_merge_20220203_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilephoto',
            options={'ordering': ['-url']},
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
