# Generated by Django 4.0.1 on 2022-02-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_merge_20220203_0008'),
        ('main_app', '0015_alter_profilephoto_options_alter_profilephoto_url'),
    ]

    operations = [
    ]
